% Decide which files to include in release
files = [
	"adaptation.c",...
	"compile_mex.m",...
	"complex.c",...
	"complex.hpp",...
	"demo.m",...
	"ffGn.m",...
	"model.c",...
	"README.md",...
	"sfie.c",...
	"sim_efferent_model.m",...
	"sim_efferent_model_mex.c"...
];

% Create filename
filename = strcat("efferent_model", "_", string(datetime("today", "Format", "yyyy-MM-dd")), ".zip");

% Create zip
zip(filename, files);